name: GitHub Action 

on: 
  push:
    branches:    
      - dev
  pull_request:
    branches:    
      - master

jobs:
  deploy:
    name: GitHub Pipeline
    runs-on: macos-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Selecting Xcode Version
        run: sudo xcode-select -switch /Applications/Xcode_16.0.app
        
      - name: Running Xcode version Is?
        run: /usr/bin/xcodebuild -version
   
      - name: Build Cleanup
        run: |
          xcodebuild clean -project GitHubAction.xcodeproj -scheme GitHubAction | xcpretty
          
      - name: Build Archive
        uses: yukiarrr/ios-build-action@v1.5.0  
        with:
          project-path: GitHubAction.xcodeproj
          workspace-path: GitHubAction.xcworkspace # optional
          scheme: GitHubAction
          configuration: Release
          export-method: app-store
          p12-key-base64: ${{ secrets.P12_KEY_BASE64 }}
          p12-cer-base64: ${{ secrets.P12_CER_BASE64 }}
          mobileprovision-base64: ${{ secrets.MOBILEPROVISION_BASE64 }}
          code-signing-identity: ${{ secrets.CODE_SIGNING_IDENTITY }}
          team-id: ${{ secrets.TEAM_ID }}
    
      - name: Saving IPA File
        uses: actions/upload-artifact@v2   
        with:
          name: ipa
          path: ./**.ipa
          
      - name: Upload App
        if: success()
        env:
          APPLEID_USERNAME: ${{ secrets.APPLEID_USERNAME }}
          APPLEID_PASSWORD: ${{ secrets.APPLEID_PASSWORD }}
        run: |
          xcrun altool --upload-app -t ios -f ./**.ipa -u "$APPLEID_USERNAME" -p "$APPLEID_PASSWORD" --verbose
